/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicitarRouteImport } from './routes/publicitar'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as GaleriasRouteImport } from './routes/galerias'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as CategoriasIdRouteImport } from './routes/categorias.$id'

const PublicitarRoute = PublicitarRouteImport.update({
  id: '/publicitar',
  path: '/publicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriasRoute = GaleriasRouteImport.update({
  id: '/galerias',
  path: '/galerias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriasRoute,
} as any)
const CategoriasIdRoute = CategoriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CategoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/galerias': typeof GaleriasRoute
  '/nosotros': typeof NosotrosRoute
  '/publicitar': typeof PublicitarRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/categorias/': typeof CategoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/galerias': typeof GaleriasRoute
  '/nosotros': typeof NosotrosRoute
  '/publicitar': typeof PublicitarRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/categorias': typeof CategoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/galerias': typeof GaleriasRoute
  '/nosotros': typeof NosotrosRoute
  '/publicitar': typeof PublicitarRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/categorias/': typeof CategoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/contacto'
    | '/galerias'
    | '/nosotros'
    | '/publicitar'
    | '/categorias/$id'
    | '/categorias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/galerias'
    | '/nosotros'
    | '/publicitar'
    | '/categorias/$id'
    | '/categorias'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/contacto'
    | '/galerias'
    | '/nosotros'
    | '/publicitar'
    | '/categorias/$id'
    | '/categorias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  GaleriasRoute: typeof GaleriasRoute
  NosotrosRoute: typeof NosotrosRoute
  PublicitarRoute: typeof PublicitarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicitar': {
      id: '/publicitar'
      path: '/publicitar'
      fullPath: '/publicitar'
      preLoaderRoute: typeof PublicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerias': {
      id: '/galerias'
      path: '/galerias'
      fullPath: '/galerias'
      preLoaderRoute: typeof GaleriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/categorias/$id': {
      id: '/categorias/$id'
      path: '/$id'
      fullPath: '/categorias/$id'
      preLoaderRoute: typeof CategoriasIdRouteImport
      parentRoute: typeof CategoriasRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasIdRoute: typeof CategoriasIdRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasIdRoute: CategoriasIdRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  ContactoRoute: ContactoRoute,
  GaleriasRoute: GaleriasRoute,
  NosotrosRoute: NosotrosRoute,
  PublicitarRoute: PublicitarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
