# Generated by Django 5.2.12 on 2026-05-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to='base.delegate'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='base.team'),
        ),
    ]
