# Generated by Django 5.2.12 on 2026-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_category_options_alter_delegate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Equipo Activo'),
        ),
    ]
