# Generated by Django 5.2.12 on 2026-05-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_saldosocio_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Torneo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='base.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Zona')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='base.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['order'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ZoneTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos')),
                ('played', models.IntegerField(default=0, verbose_name='PJ')),
                ('won', models.IntegerField(default=0, verbose_name='PG')),
                ('drawn', models.IntegerField(default=0, verbose_name='PE')),
                ('lost', models.IntegerField(default=0, verbose_name='PP')),
                ('goals_for', models.IntegerField(default=0, verbose_name='GF')),
                ('goals_against', models.IntegerField(default=0, verbose_name='GC')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_teams', to='base.team', verbose_name='Equipo')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_teams', to='base.tournamentzone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Equipo en Zona',
                'verbose_name_plural': 'Equipos en Zona',
                'unique_together': {('zone', 'team')},
            },
        ),
    ]
