# Generated by Django 5.2.3 on 2026-05-19 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('excerpt', models.TextField(verbose_name='Resumen')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
