# Generated by Django 5.2.3 on 2026-05-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Fecha')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio general')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('tournament_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_rounds', to='base.tournamentzone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_score', models.IntegerField(blank=True, null=True, verbose_name='Goles Local')),
                ('visitor_score', models.IntegerField(blank=True, null=True, verbose_name='Goles Visitante')),
                ('played', models.BooleanField(default=False, verbose_name='Jugado')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha (específica)')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora (específica)')),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to='base.team', verbose_name='Equipo Local')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_matches', to='base.team', verbose_name='Equipo Visitante')),
                ('match_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='base.matchround', verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
    ]
