# Generated by Django 5.2.3 on 2026-05-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_matchround_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cancha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cancha'),
        ),
        migrations.AddField(
            model_name='match',
            name='impact_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_matches', to='base.tournamentzone', verbose_name='Zona de Impacto'),
        ),
    ]
