# Generated by Django 5.2.3 on 2026-06-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_match_cancha_match_impact_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200, verbose_name='Nombre del Jugador')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Goles')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleadores', to='base.team', verbose_name='Equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleadores', to='base.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Goleador',
                'verbose_name_plural': 'Goleadores',
                'ordering': ['-goals', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='Sancionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200, verbose_name='Nombre del Jugador')),
                ('reason', models.CharField(max_length=255, verbose_name='Razón/Sanción')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sancionados', to='base.team', verbose_name='Equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sancionados', to='base.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Sancionado',
                'verbose_name_plural': 'Sancionados',
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='VallaMenosVencida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200, verbose_name='Nombre del Jugador/Arquero')),
                ('goals_against', models.IntegerField(default=0, verbose_name='Goles en Contra')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vallas', to='base.team', verbose_name='Equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vallas', to='base.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Valla Menos Vencida',
                'verbose_name_plural': 'Vallas Menos Vencidas',
                'ordering': ['goals_against', 'player_name'],
            },
        ),
    ]
