# Generated by Django 5.2.3 on 2026-06-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_goleador_sancionado_vallamenosvencida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/', verbose_name='Foto de Perfil')),
                ('dni_front', models.ImageField(blank=True, null=True, upload_to='players/dni_front/', verbose_name='Foto DNI (Frente)')),
                ('dni_back', models.ImageField(blank=True, null=True, upload_to='players/dni_back/', verbose_name='Foto DNI (Dorso)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players_buena_fe',
            field=models.PositiveIntegerField(default=25, verbose_name='Máximo de Jugadores Lista Buena Fe'),
        ),
        migrations.CreateModel(
            name='GoodFaithList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de Camiseta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito el')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_faith_records', to='base.team', verbose_name='Equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_faith_records', to='base.tournament', verbose_name='Torneo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_faith_records', to='base.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Lista de Buena Fe',
                'verbose_name_plural': 'Listas de Buena Fe',
                'unique_together': {('tournament', 'team', 'player')},
            },
        ),
    ]
