# Generated by Django 6.0.6 on 2026-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delegate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneteam',
            name='fair_play',
            field=models.IntegerField(default=0, verbose_name='Fair Play'),
        ),
        migrations.AddField(
            model_name='zoneteam',
            name='indumentaria',
            field=models.IntegerField(default=0, verbose_name='Indumentaria'),
        ),
        migrations.AddField(
            model_name='zoneteam',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Tarjetas Rojas'),
        ),
        migrations.AddField(
            model_name='zoneteam',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Tarjetas Amarillas'),
        ),
    ]
