# Generated by Django 6.0.6 on 2026-07-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_zoneteam_fair_play_zoneteam_indumentaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_birthday_in_year',
            field=models.BooleanField(default=False, verbose_name='Permitir si cumple años en el transcurso del año'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('sin_restriccion', 'Sin restricción de edad'), ('libre', 'Libre (Mayores de 18 años)'), ('veteranos', 'Veteranos')], default='sin_restriccion', max_length=30, verbose_name='Tipo de Categoría'),
        ),
        migrations.AddField(
            model_name='category',
            name='football_type',
            field=models.CharField(choices=[('Futbol 5', 'Fútbol 5'), ('Futbol 6', 'Fútbol 6'), ('Futbol 7', 'Fútbol 7'), ('Futbol 8', 'Fútbol 8'), ('Futbol 9', 'Fútbol 9'), ('Futbol 10', 'Fútbol 10'), ('Futbol 11', 'Fútbol 11'), ('Otros', 'Otros')], default='Futbol 11', max_length=20, verbose_name='Tipo de Fútbol'),
        ),
        migrations.AddField(
            model_name='category',
            name='max_underage_allowed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Menores Permitidos'),
        ),
        migrations.AddField(
            model_name='category',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad Mínima (Veteranos)'),
        ),
    ]
