# Generated by Django 6.0.6 on 2026-07-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_category_allow_birthday_in_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_underage_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad Mínima de Menores (Senior)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('sin_restriccion', 'Sin restricción de edad'), ('libre', 'Libre (Mayores de 18 años)'), ('senior', 'Senior')], default='sin_restriccion', max_length=30, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad Mínima (Senior)'),
        ),
    ]
