# Generated by Django 6.0.6 on 2026-07-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_category_min_underage_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='base.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='base.category', verbose_name='Categoría'),
        ),
    ]
