# Generated by Django 5.2.3 on 2026-08-07 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_team_category_alter_tournament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='half_duration',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Duración de cada Tiempo'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_1',
            field=models.CharField(default='Puntos', max_length=50, verbose_name='Criterio 1'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_2',
            field=models.CharField(default='Dif. de goles', max_length=50, verbose_name='Criterio 2'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_3',
            field=models.CharField(default='Goles a favor', max_length=50, verbose_name='Criterio 3'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_4',
            field=models.CharField(default='Fair Play', max_length=50, verbose_name='Criterio 4'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_5',
            field=models.CharField(default='Resultado entre ellos', max_length=50, verbose_name='Criterio 5'),
        ),
    ]
