# Generated by Django 5.2.3 on 2026-08-07 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_tournament_half_duration_tournament_tiebreaker_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fp_blue_card_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar Tarjeta Azul'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_blue_pts',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Puntos Tarjeta Azul'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_red_direct_pts',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Puntos Tarjeta Roja Directa'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_red_indirect_pts',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Puntos Tarjeta Roja Indirecta'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_wo_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar Puntos por WO'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_wo_pts',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Puntos por WO'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_yellow_pts',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Puntos Tarjeta Amarilla'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='half_duration',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Duración de cada Tiempo'),
        ),
    ]
