# Generated by Django 5.2.3 on 2026-08-07 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_tournament_fp_blue_card_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='fp_red_direct_pts',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='fp_red_indirect_pts',
        ),
        migrations.AddField(
            model_name='tournament',
            name='fp_red_pts',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Puntos Tarjeta Roja'),
        ),
    ]
