# Generated by Django 5.2.3 on 2026-08-11 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_tournament_fp_red_direct_pts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Modalidad del Torneo'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_draw',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puntos por Partido Empatado'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_loss',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puntos por Partido Perdido'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_win',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntos por Partido Ganado'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='yellow_cards_suspension',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Amarillas para Suspensión'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players_buena_fe',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Máximo de Jugadores Lista Buena Fe'),
        ),
    ]
