# Generated by Django 6.0.6 on 2026-09-15 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_tournament_description_tournament_pts_draw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='half_duration',
            field=models.PositiveIntegerField(default=35, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Duración de cada Tiempo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players_buena_fe',
            field=models.PositiveIntegerField(blank=True, default=25, null=True, verbose_name='Máximo de Jugadores Lista Buena Fe'),
        ),
    ]
