# Generated by Django 6.0.6 on 2026-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_tournament_half_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='arbitro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Árbitro'),
        ),
    ]
