# Generated by Django 6.0.6 on 2026-09-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_match_arbitro'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='penalties',
            field=models.BooleanField(default=False, verbose_name='Penales'),
        ),
        migrations.AddField(
            model_name='match',
            name='points_awarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_matches', to='base.team', verbose_name='Puntos Otorgados a'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='FINALIZADO', max_length=30, verbose_name='Estado del Partido'),
        ),
        migrations.CreateModel(
            name='MatchPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Goles')),
                ('yellow_card', models.BooleanField(default=False, verbose_name='Tarjeta Amarilla')),
                ('red_card', models.BooleanField(default=False, verbose_name='Tarjeta Roja')),
                ('red_card_suspension_dates', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fechas de Suspensión')),
                ('red_card_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Suspensión')),
                ('is_figura', models.BooleanField(default=False, verbose_name='Figura')),
                ('played', models.BooleanField(default=False, verbose_name='Jugó')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='base.match', verbose_name='Partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='base.player', verbose_name='Jugador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_stats', to='base.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador en Partido',
                'verbose_name_plural': 'Estadísticas de Jugadores en Partidos',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
