# Generated by Django 6.0.6 on 2026-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_match_penalties_match_points_awarded_to_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='local_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penales Local'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penales Visitante'),
        ),
    ]
